// ==============================================================
// Generated by Vitis HLS v2025.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="winograd_winograd,hls_ip_2025_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcvu440_CIV-flgb2377-1-i,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.300000,HLS_SYN_LAT=96,HLS_SYN_TPT=none,HLS_SYN_MEM=2,HLS_SYN_DSP=0,HLS_SYN_FF=6393,HLS_SYN_LUT=4539,HLS_VERSION=2025_1}" *)

module winograd (
        ap_clk,
        ap_rst_n,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        s_axi_CTRL_AWVALID,
        s_axi_CTRL_AWREADY,
        s_axi_CTRL_AWADDR,
        s_axi_CTRL_WVALID,
        s_axi_CTRL_WREADY,
        s_axi_CTRL_WDATA,
        s_axi_CTRL_WSTRB,
        s_axi_CTRL_ARVALID,
        s_axi_CTRL_ARREADY,
        s_axi_CTRL_ARADDR,
        s_axi_CTRL_RVALID,
        s_axi_CTRL_RREADY,
        s_axi_CTRL_RDATA,
        s_axi_CTRL_RRESP,
        s_axi_CTRL_BVALID,
        s_axi_CTRL_BREADY,
        s_axi_CTRL_BRESP,
        interrupt
);

parameter    ap_ST_fsm_state1 = 64'd1;
parameter    ap_ST_fsm_state2 = 64'd2;
parameter    ap_ST_fsm_state3 = 64'd4;
parameter    ap_ST_fsm_state4 = 64'd8;
parameter    ap_ST_fsm_state5 = 64'd16;
parameter    ap_ST_fsm_state6 = 64'd32;
parameter    ap_ST_fsm_state7 = 64'd64;
parameter    ap_ST_fsm_state8 = 64'd128;
parameter    ap_ST_fsm_state9 = 64'd256;
parameter    ap_ST_fsm_state10 = 64'd512;
parameter    ap_ST_fsm_state11 = 64'd1024;
parameter    ap_ST_fsm_state12 = 64'd2048;
parameter    ap_ST_fsm_state13 = 64'd4096;
parameter    ap_ST_fsm_state14 = 64'd8192;
parameter    ap_ST_fsm_state15 = 64'd16384;
parameter    ap_ST_fsm_state16 = 64'd32768;
parameter    ap_ST_fsm_state17 = 64'd65536;
parameter    ap_ST_fsm_state18 = 64'd131072;
parameter    ap_ST_fsm_state19 = 64'd262144;
parameter    ap_ST_fsm_state20 = 64'd524288;
parameter    ap_ST_fsm_state21 = 64'd1048576;
parameter    ap_ST_fsm_state22 = 64'd2097152;
parameter    ap_ST_fsm_state23 = 64'd4194304;
parameter    ap_ST_fsm_state24 = 64'd8388608;
parameter    ap_ST_fsm_state25 = 64'd16777216;
parameter    ap_ST_fsm_state26 = 64'd33554432;
parameter    ap_ST_fsm_state27 = 64'd67108864;
parameter    ap_ST_fsm_state28 = 64'd134217728;
parameter    ap_ST_fsm_state29 = 64'd268435456;
parameter    ap_ST_fsm_state30 = 64'd536870912;
parameter    ap_ST_fsm_state31 = 64'd1073741824;
parameter    ap_ST_fsm_state32 = 64'd2147483648;
parameter    ap_ST_fsm_state33 = 64'd4294967296;
parameter    ap_ST_fsm_state34 = 64'd8589934592;
parameter    ap_ST_fsm_state35 = 64'd17179869184;
parameter    ap_ST_fsm_state36 = 64'd34359738368;
parameter    ap_ST_fsm_state37 = 64'd68719476736;
parameter    ap_ST_fsm_state38 = 64'd137438953472;
parameter    ap_ST_fsm_state39 = 64'd274877906944;
parameter    ap_ST_fsm_state40 = 64'd549755813888;
parameter    ap_ST_fsm_state41 = 64'd1099511627776;
parameter    ap_ST_fsm_state42 = 64'd2199023255552;
parameter    ap_ST_fsm_state43 = 64'd4398046511104;
parameter    ap_ST_fsm_state44 = 64'd8796093022208;
parameter    ap_ST_fsm_state45 = 64'd17592186044416;
parameter    ap_ST_fsm_state46 = 64'd35184372088832;
parameter    ap_ST_fsm_state47 = 64'd70368744177664;
parameter    ap_ST_fsm_state48 = 64'd140737488355328;
parameter    ap_ST_fsm_state49 = 64'd281474976710656;
parameter    ap_ST_fsm_state50 = 64'd562949953421312;
parameter    ap_ST_fsm_state51 = 64'd1125899906842624;
parameter    ap_ST_fsm_state52 = 64'd2251799813685248;
parameter    ap_ST_fsm_state53 = 64'd4503599627370496;
parameter    ap_ST_fsm_state54 = 64'd9007199254740992;
parameter    ap_ST_fsm_state55 = 64'd18014398509481984;
parameter    ap_ST_fsm_state56 = 64'd36028797018963968;
parameter    ap_ST_fsm_state57 = 64'd72057594037927936;
parameter    ap_ST_fsm_state58 = 64'd144115188075855872;
parameter    ap_ST_fsm_state59 = 64'd288230376151711744;
parameter    ap_ST_fsm_state60 = 64'd576460752303423488;
parameter    ap_ST_fsm_state61 = 64'd1152921504606846976;
parameter    ap_ST_fsm_state62 = 64'd2305843009213693952;
parameter    ap_ST_fsm_state63 = 64'd4611686018427387904;
parameter    ap_ST_fsm_state64 = 64'd9223372036854775808;
parameter    C_S_AXI_CTRL_DATA_WIDTH = 32;
parameter    C_S_AXI_CTRL_ADDR_WIDTH = 6;
parameter    C_S_AXI_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_ID_WIDTH = 1;
parameter    C_M_AXI_GMEM_ADDR_WIDTH = 64;
parameter    C_M_AXI_GMEM_DATA_WIDTH = 32;
parameter    C_M_AXI_GMEM_AWUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_ARUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_WUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_RUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_BUSER_WIDTH = 1;
parameter    C_M_AXI_GMEM_USER_VALUE = 0;
parameter    C_M_AXI_GMEM_PROT_VALUE = 0;
parameter    C_M_AXI_GMEM_CACHE_VALUE = 3;
parameter    C_M_AXI_DATA_WIDTH = 32;

parameter C_S_AXI_CTRL_WSTRB_WIDTH = (32 / 8);
parameter C_S_AXI_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_GMEM_WSTRB_WIDTH = (32 / 8);
parameter C_M_AXI_WSTRB_WIDTH = (32 / 8);

input   ap_clk;
input   ap_rst_n;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_AWADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_AWID;
output  [7:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [C_M_AXI_GMEM_AWUSER_WIDTH - 1:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_WDATA;
output  [C_M_AXI_GMEM_WSTRB_WIDTH - 1:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_WID;
output  [C_M_AXI_GMEM_WUSER_WIDTH - 1:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [C_M_AXI_GMEM_ADDR_WIDTH - 1:0] m_axi_gmem_ARADDR;
output  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_ARID;
output  [7:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [C_M_AXI_GMEM_ARUSER_WIDTH - 1:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [C_M_AXI_GMEM_DATA_WIDTH - 1:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_RID;
input  [C_M_AXI_GMEM_RUSER_WIDTH - 1:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [C_M_AXI_GMEM_ID_WIDTH - 1:0] m_axi_gmem_BID;
input  [C_M_AXI_GMEM_BUSER_WIDTH - 1:0] m_axi_gmem_BUSER;
input   s_axi_CTRL_AWVALID;
output   s_axi_CTRL_AWREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_AWADDR;
input   s_axi_CTRL_WVALID;
output   s_axi_CTRL_WREADY;
input  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_WDATA;
input  [C_S_AXI_CTRL_WSTRB_WIDTH - 1:0] s_axi_CTRL_WSTRB;
input   s_axi_CTRL_ARVALID;
output   s_axi_CTRL_ARREADY;
input  [C_S_AXI_CTRL_ADDR_WIDTH - 1:0] s_axi_CTRL_ARADDR;
output   s_axi_CTRL_RVALID;
input   s_axi_CTRL_RREADY;
output  [C_S_AXI_CTRL_DATA_WIDTH - 1:0] s_axi_CTRL_RDATA;
output  [1:0] s_axi_CTRL_RRESP;
output   s_axi_CTRL_BVALID;
input   s_axi_CTRL_BREADY;
output  [1:0] s_axi_CTRL_BRESP;
output   interrupt;

 reg    ap_rst_n_inv;
wire    ap_start;
reg    ap_done;
reg    ap_idle;
(* fsm_encoding = "none" *) reg   [63:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_ready;
wire   [63:0] in_g;
wire   [63:0] in_d;
wire   [63:0] out_y;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state12;
reg    gmem_blk_n_AW;
wire    ap_CS_fsm_state55;
reg    gmem_blk_n_W;
wire    ap_CS_fsm_state56;
wire    ap_CS_fsm_state57;
wire    ap_CS_fsm_state58;
wire    ap_CS_fsm_state59;
reg    gmem_blk_n_B;
wire    ap_CS_fsm_state64;
wire   [31:0] grp_fu_281_p2;
reg   [31:0] reg_323;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state21;
wire    grp_winograd_Pipeline_read_d_fu_250_ap_done;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_state30;
wire    ap_CS_fsm_state34;
wire    ap_CS_fsm_state39;
wire    ap_CS_fsm_state43;
wire    ap_CS_fsm_state48;
wire   [31:0] grp_fu_285_p2;
reg   [31:0] reg_331;
wire    ap_CS_fsm_state29;
wire    ap_CS_fsm_state44;
wire    ap_CS_fsm_state53;
wire   [31:0] grp_fu_289_p2;
reg   [31:0] reg_342;
wire   [31:0] grp_fu_308_p2;
reg   [31:0] reg_351;
wire    ap_CS_fsm_state38;
wire   [31:0] grp_fu_313_p2;
reg   [31:0] reg_361;
reg   [31:0] reg_370;
wire    ap_CS_fsm_state26;
wire    ap_CS_fsm_state35;
wire   [31:0] grp_fu_293_p2;
reg   [31:0] reg_376;
reg   [31:0] reg_383;
reg   [31:0] reg_389;
reg   [31:0] reg_395;
reg   [31:0] reg_401;
wire   [31:0] grp_fu_318_p2;
reg   [31:0] reg_408;
reg   [61:0] trunc_ln_reg_814;
reg   [61:0] trunc_ln1_reg_820;
reg   [63:0] gmem_addr_2_reg_826;
reg   [31:0] sub1_reg_897;
wire   [31:0] grp_fu_297_p2;
reg   [31:0] sub160_2_reg_903;
wire   [31:0] grp_fu_301_p2;
reg   [31:0] add170_2_reg_909;
reg   [31:0] mul_1_2_reg_916;
reg   [31:0] sub131_1_reg_923;
reg   [31:0] sub209_1_reg_928;
reg   [31:0] add230_1_reg_933;
reg   [31:0] mul266_1_reg_938;
wire   [31:0] bitcast_ln93_1_fu_592_p1;
wire    ap_CS_fsm_state45;
wire   [31:0] bitcast_ln93_3_fu_627_p1;
wire    grp_winograd_Pipeline_read_g_fu_234_ap_start;
wire    grp_winograd_Pipeline_read_g_fu_234_ap_done;
wire    grp_winograd_Pipeline_read_g_fu_234_ap_idle;
wire    grp_winograd_Pipeline_read_g_fu_234_ap_ready;
wire    grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWID;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWUSER;
wire    grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WVALID;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WDATA;
wire   [3:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WSTRB;
wire    grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WLAST;
wire   [0:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WID;
wire   [0:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WUSER;
wire    grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARID;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARUSER;
wire    grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_RREADY;
wire    grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_BREADY;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_g_load_out;
wire    grp_winograd_Pipeline_read_g_fu_234_g_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_g_1_load_out;
wire    grp_winograd_Pipeline_read_g_fu_234_g_1_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_g_2_load_out;
wire    grp_winograd_Pipeline_read_g_fu_234_g_2_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_g_3_load_out;
wire    grp_winograd_Pipeline_read_g_fu_234_g_3_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_g_4_load_out;
wire    grp_winograd_Pipeline_read_g_fu_234_g_4_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_g_5_load_out;
wire    grp_winograd_Pipeline_read_g_fu_234_g_5_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_g_6_load_out;
wire    grp_winograd_Pipeline_read_g_fu_234_g_6_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_g_7_load_out;
wire    grp_winograd_Pipeline_read_g_fu_234_g_7_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_g_fu_234_g_8_load_out;
wire    grp_winograd_Pipeline_read_g_fu_234_g_8_load_out_ap_vld;
wire    grp_winograd_Pipeline_read_d_fu_250_ap_start;
wire    grp_winograd_Pipeline_read_d_fu_250_ap_idle;
wire    grp_winograd_Pipeline_read_d_fu_250_ap_ready;
wire    grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWVALID;
wire   [63:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWADDR;
wire   [0:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWID;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWLEN;
wire   [2:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWSIZE;
wire   [1:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWBURST;
wire   [1:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWLOCK;
wire   [3:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWCACHE;
wire   [2:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWPROT;
wire   [3:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWQOS;
wire   [3:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWREGION;
wire   [0:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWUSER;
wire    grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WVALID;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WDATA;
wire   [3:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WSTRB;
wire    grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WLAST;
wire   [0:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WID;
wire   [0:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WUSER;
wire    grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARVALID;
wire   [63:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARADDR;
wire   [0:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARID;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARLEN;
wire   [2:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARSIZE;
wire   [1:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARBURST;
wire   [1:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARLOCK;
wire   [3:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARCACHE;
wire   [2:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARPROT;
wire   [3:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARQOS;
wire   [3:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARREGION;
wire   [0:0] grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARUSER;
wire    grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_RREADY;
wire    grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_BREADY;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_1_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_1_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_2_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_2_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_3_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_3_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_4_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_4_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_5_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_5_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_6_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_6_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_7_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_7_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_8_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_8_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_9_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_9_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_10_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_10_load_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_read_d_fu_250_d_11_load_out;
wire    grp_winograd_Pipeline_read_d_fu_250_d_11_load_out_ap_vld;
wire    grp_winograd_Pipeline_compute_Y_fu_269_ap_start;
wire    grp_winograd_Pipeline_compute_Y_fu_269_ap_done;
wire    grp_winograd_Pipeline_compute_Y_fu_269_ap_idle;
wire    grp_winograd_Pipeline_compute_Y_fu_269_ap_ready;
wire   [31:0] grp_winograd_Pipeline_compute_Y_fu_269_p_out;
wire    grp_winograd_Pipeline_compute_Y_fu_269_p_out_ap_vld;
wire   [31:0] grp_winograd_Pipeline_compute_Y_fu_269_p_out1;
wire    grp_winograd_Pipeline_compute_Y_fu_269_p_out1_ap_vld;
wire   [31:0] grp_winograd_Pipeline_compute_Y_fu_269_p_out2;
wire    grp_winograd_Pipeline_compute_Y_fu_269_p_out2_ap_vld;
wire   [31:0] grp_winograd_Pipeline_compute_Y_fu_269_p_out3;
wire    grp_winograd_Pipeline_compute_Y_fu_269_p_out3_ap_vld;
reg    gmem_0_AWVALID;
wire    gmem_0_AWREADY;
wire   [31:0] gmem_0_AWLEN;
reg    gmem_0_WVALID;
wire    gmem_0_WREADY;
reg   [31:0] gmem_0_WDATA;
reg    gmem_0_ARVALID;
wire    gmem_0_ARREADY;
reg   [63:0] gmem_0_ARADDR;
reg   [31:0] gmem_0_ARLEN;
wire    gmem_0_RVALID;
reg    gmem_0_RREADY;
wire   [31:0] gmem_0_RDATA;
wire   [8:0] gmem_0_RFIFONUM;
wire    gmem_0_BVALID;
reg    gmem_0_BREADY;
reg    grp_winograd_Pipeline_read_g_fu_234_ap_start_reg;
wire    ap_CS_fsm_state9;
reg   [63:0] ap_NS_fsm;
wire    ap_NS_fsm_state10;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
reg    grp_winograd_Pipeline_read_d_fu_250_ap_start_reg;
wire    ap_CS_fsm_state19;
wire    ap_NS_fsm_state20;
wire    ap_CS_fsm_state20;
reg    grp_winograd_Pipeline_compute_Y_fu_269_ap_start_reg;
wire    ap_CS_fsm_state54;
wire  signed [63:0] sext_ln127_fu_444_p1;
wire  signed [63:0] sext_ln34_fu_454_p1;
wire  signed [63:0] sext_ln45_fu_480_p1;
wire   [31:0] bitcast_ln127_fu_635_p1;
wire   [31:0] bitcast_ln127_1_fu_643_p1;
wire   [31:0] bitcast_ln127_2_fu_651_p1;
wire   [31:0] bitcast_ln127_3_fu_659_p1;
wire    ap_CS_fsm_state40;
wire    ap_CS_fsm_state22;
wire    ap_CS_fsm_state17;
reg   [31:0] grp_fu_281_p0;
reg   [31:0] grp_fu_281_p1;
wire    ap_CS_fsm_state31;
wire    ap_CS_fsm_state49;
reg   [31:0] grp_fu_285_p0;
reg   [31:0] grp_fu_285_p1;
reg   [31:0] grp_fu_289_p0;
reg   [31:0] grp_fu_289_p1;
reg   [31:0] grp_fu_293_p0;
reg   [31:0] grp_fu_293_p1;
reg   [31:0] grp_fu_297_p0;
reg   [31:0] grp_fu_297_p1;
reg   [31:0] grp_fu_308_p0;
reg   [31:0] grp_fu_308_p1;
wire    ap_CS_fsm_state27;
wire    ap_CS_fsm_state36;
reg   [31:0] grp_fu_313_p0;
reg   [31:0] grp_fu_313_p1;
reg   [31:0] grp_fu_318_p0;
reg   [31:0] grp_fu_318_p1;
wire   [61:0] trunc_ln2_fu_434_p4;
wire   [31:0] bitcast_ln93_fu_562_p1;
wire   [0:0] bit_sel1_fu_566_p3;
wire   [0:0] xor_ln93_2_fu_574_p2;
wire   [30:0] trunc_ln93_fu_580_p1;
wire   [31:0] xor_ln_fu_584_p3;
wire   [31:0] bitcast_ln93_2_fu_597_p1;
wire   [0:0] bit_sel_fu_601_p3;
wire   [0:0] xor_ln93_fu_609_p2;
wire   [30:0] trunc_ln93_1_fu_615_p1;
wire   [31:0] xor_ln93_1_fu_619_p3;
reg   [1:0] grp_fu_281_opcode;
reg    grp_fu_281_ce;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_state23;
wire    ap_CS_fsm_state24;
wire    ap_CS_fsm_state28;
wire    ap_CS_fsm_state32;
wire    ap_CS_fsm_state33;
wire    ap_CS_fsm_state37;
wire    ap_CS_fsm_state46;
wire    ap_CS_fsm_state47;
wire    ap_CS_fsm_state50;
wire    ap_CS_fsm_state51;
wire    ap_CS_fsm_state52;
wire    ap_CS_fsm_state3;
wire    ap_CS_fsm_state4;
wire    ap_CS_fsm_state5;
wire    ap_CS_fsm_state6;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_state8;
wire    ap_CS_fsm_state60;
wire    ap_CS_fsm_state61;
wire    ap_CS_fsm_state62;
wire    ap_CS_fsm_state63;
reg   [1:0] grp_fu_285_opcode;
reg    grp_fu_285_ce;
reg   [1:0] grp_fu_289_opcode;
reg    grp_fu_289_ce;
reg   [1:0] grp_fu_293_opcode;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
wire    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
wire    ap_ST_fsm_state14_blk;
wire    ap_ST_fsm_state15_blk;
wire    ap_ST_fsm_state16_blk;
wire    ap_ST_fsm_state17_blk;
wire    ap_ST_fsm_state18_blk;
wire    ap_ST_fsm_state19_blk;
wire    ap_ST_fsm_state20_blk;
reg    ap_ST_fsm_state21_blk;
wire    ap_ST_fsm_state22_blk;
wire    ap_ST_fsm_state23_blk;
wire    ap_ST_fsm_state24_blk;
wire    ap_ST_fsm_state25_blk;
wire    ap_ST_fsm_state26_blk;
wire    ap_ST_fsm_state27_blk;
wire    ap_ST_fsm_state28_blk;
wire    ap_ST_fsm_state29_blk;
wire    ap_ST_fsm_state30_blk;
wire    ap_ST_fsm_state31_blk;
wire    ap_ST_fsm_state32_blk;
wire    ap_ST_fsm_state33_blk;
wire    ap_ST_fsm_state34_blk;
wire    ap_ST_fsm_state35_blk;
wire    ap_ST_fsm_state36_blk;
wire    ap_ST_fsm_state37_blk;
wire    ap_ST_fsm_state38_blk;
wire    ap_ST_fsm_state39_blk;
wire    ap_ST_fsm_state40_blk;
wire    ap_ST_fsm_state41_blk;
wire    ap_ST_fsm_state42_blk;
wire    ap_ST_fsm_state43_blk;
wire    ap_ST_fsm_state44_blk;
wire    ap_ST_fsm_state45_blk;
wire    ap_ST_fsm_state46_blk;
wire    ap_ST_fsm_state47_blk;
wire    ap_ST_fsm_state48_blk;
wire    ap_ST_fsm_state49_blk;
wire    ap_ST_fsm_state50_blk;
wire    ap_ST_fsm_state51_blk;
wire    ap_ST_fsm_state52_blk;
wire    ap_ST_fsm_state53_blk;
reg    ap_ST_fsm_state54_blk;
reg    ap_ST_fsm_state55_blk;
reg    ap_ST_fsm_state56_blk;
reg    ap_ST_fsm_state57_blk;
reg    ap_ST_fsm_state58_blk;
reg    ap_ST_fsm_state59_blk;
wire    ap_ST_fsm_state60_blk;
wire    ap_ST_fsm_state61_blk;
wire    ap_ST_fsm_state62_blk;
wire    ap_ST_fsm_state63_blk;
reg    ap_ST_fsm_state64_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 64'd1;
#0 grp_winograd_Pipeline_read_g_fu_234_ap_start_reg = 1'b0;
#0 grp_winograd_Pipeline_read_d_fu_250_ap_start_reg = 1'b0;
#0 grp_winograd_Pipeline_compute_Y_fu_269_ap_start_reg = 1'b0;
end

winograd_winograd_Pipeline_read_g grp_winograd_Pipeline_read_g_fu_234(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_winograd_Pipeline_read_g_fu_234_ap_start),
    .ap_done(grp_winograd_Pipeline_read_g_fu_234_ap_done),
    .ap_idle(grp_winograd_Pipeline_read_g_fu_234_ap_idle),
    .ap_ready(grp_winograd_Pipeline_read_g_fu_234_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(1'b0),
    .m_axi_gmem_0_AWADDR(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(1'b0),
    .m_axi_gmem_0_WDATA(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(1'b0),
    .m_axi_gmem_0_BREADY(grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .sext_ln34(trunc_ln_reg_814),
    .g_load_out(grp_winograd_Pipeline_read_g_fu_234_g_load_out),
    .g_load_out_ap_vld(grp_winograd_Pipeline_read_g_fu_234_g_load_out_ap_vld),
    .g_1_load_out(grp_winograd_Pipeline_read_g_fu_234_g_1_load_out),
    .g_1_load_out_ap_vld(grp_winograd_Pipeline_read_g_fu_234_g_1_load_out_ap_vld),
    .g_2_load_out(grp_winograd_Pipeline_read_g_fu_234_g_2_load_out),
    .g_2_load_out_ap_vld(grp_winograd_Pipeline_read_g_fu_234_g_2_load_out_ap_vld),
    .g_3_load_out(grp_winograd_Pipeline_read_g_fu_234_g_3_load_out),
    .g_3_load_out_ap_vld(grp_winograd_Pipeline_read_g_fu_234_g_3_load_out_ap_vld),
    .g_4_load_out(grp_winograd_Pipeline_read_g_fu_234_g_4_load_out),
    .g_4_load_out_ap_vld(grp_winograd_Pipeline_read_g_fu_234_g_4_load_out_ap_vld),
    .g_5_load_out(grp_winograd_Pipeline_read_g_fu_234_g_5_load_out),
    .g_5_load_out_ap_vld(grp_winograd_Pipeline_read_g_fu_234_g_5_load_out_ap_vld),
    .g_6_load_out(grp_winograd_Pipeline_read_g_fu_234_g_6_load_out),
    .g_6_load_out_ap_vld(grp_winograd_Pipeline_read_g_fu_234_g_6_load_out_ap_vld),
    .g_7_load_out(grp_winograd_Pipeline_read_g_fu_234_g_7_load_out),
    .g_7_load_out_ap_vld(grp_winograd_Pipeline_read_g_fu_234_g_7_load_out_ap_vld),
    .g_8_load_out(grp_winograd_Pipeline_read_g_fu_234_g_8_load_out),
    .g_8_load_out_ap_vld(grp_winograd_Pipeline_read_g_fu_234_g_8_load_out_ap_vld)
);

winograd_winograd_Pipeline_read_d grp_winograd_Pipeline_read_d_fu_250(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_winograd_Pipeline_read_d_fu_250_ap_start),
    .ap_done(grp_winograd_Pipeline_read_d_fu_250_ap_done),
    .ap_idle(grp_winograd_Pipeline_read_d_fu_250_ap_idle),
    .ap_ready(grp_winograd_Pipeline_read_d_fu_250_ap_ready),
    .m_axi_gmem_0_AWVALID(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWVALID),
    .m_axi_gmem_0_AWREADY(1'b0),
    .m_axi_gmem_0_AWADDR(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWADDR),
    .m_axi_gmem_0_AWID(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWID),
    .m_axi_gmem_0_AWLEN(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWLEN),
    .m_axi_gmem_0_AWSIZE(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWSIZE),
    .m_axi_gmem_0_AWBURST(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWBURST),
    .m_axi_gmem_0_AWLOCK(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWLOCK),
    .m_axi_gmem_0_AWCACHE(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWCACHE),
    .m_axi_gmem_0_AWPROT(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWPROT),
    .m_axi_gmem_0_AWQOS(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWQOS),
    .m_axi_gmem_0_AWREGION(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWREGION),
    .m_axi_gmem_0_AWUSER(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_AWUSER),
    .m_axi_gmem_0_WVALID(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WVALID),
    .m_axi_gmem_0_WREADY(1'b0),
    .m_axi_gmem_0_WDATA(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WDATA),
    .m_axi_gmem_0_WSTRB(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WSTRB),
    .m_axi_gmem_0_WLAST(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WLAST),
    .m_axi_gmem_0_WID(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WID),
    .m_axi_gmem_0_WUSER(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_WUSER),
    .m_axi_gmem_0_ARVALID(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARVALID),
    .m_axi_gmem_0_ARREADY(gmem_0_ARREADY),
    .m_axi_gmem_0_ARADDR(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARADDR),
    .m_axi_gmem_0_ARID(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARID),
    .m_axi_gmem_0_ARLEN(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARLEN),
    .m_axi_gmem_0_ARSIZE(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARSIZE),
    .m_axi_gmem_0_ARBURST(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARBURST),
    .m_axi_gmem_0_ARLOCK(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARLOCK),
    .m_axi_gmem_0_ARCACHE(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARCACHE),
    .m_axi_gmem_0_ARPROT(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARPROT),
    .m_axi_gmem_0_ARQOS(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARQOS),
    .m_axi_gmem_0_ARREGION(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARREGION),
    .m_axi_gmem_0_ARUSER(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARUSER),
    .m_axi_gmem_0_RVALID(gmem_0_RVALID),
    .m_axi_gmem_0_RREADY(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_RREADY),
    .m_axi_gmem_0_RDATA(gmem_0_RDATA),
    .m_axi_gmem_0_RLAST(1'b0),
    .m_axi_gmem_0_RID(1'd0),
    .m_axi_gmem_0_RFIFONUM(gmem_0_RFIFONUM),
    .m_axi_gmem_0_RUSER(1'd0),
    .m_axi_gmem_0_RRESP(2'd0),
    .m_axi_gmem_0_BVALID(1'b0),
    .m_axi_gmem_0_BREADY(grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_BREADY),
    .m_axi_gmem_0_BRESP(2'd0),
    .m_axi_gmem_0_BID(1'd0),
    .m_axi_gmem_0_BUSER(1'd0),
    .sext_ln45(trunc_ln1_reg_820),
    .d_load_out(grp_winograd_Pipeline_read_d_fu_250_d_load_out),
    .d_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_load_out_ap_vld),
    .d_1_load_out(grp_winograd_Pipeline_read_d_fu_250_d_1_load_out),
    .d_1_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_1_load_out_ap_vld),
    .d_2_load_out(grp_winograd_Pipeline_read_d_fu_250_d_2_load_out),
    .d_2_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_2_load_out_ap_vld),
    .d_3_load_out(grp_winograd_Pipeline_read_d_fu_250_d_3_load_out),
    .d_3_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_3_load_out_ap_vld),
    .d_4_load_out(grp_winograd_Pipeline_read_d_fu_250_d_4_load_out),
    .d_4_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_4_load_out_ap_vld),
    .d_5_load_out(grp_winograd_Pipeline_read_d_fu_250_d_5_load_out),
    .d_5_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_5_load_out_ap_vld),
    .d_6_load_out(grp_winograd_Pipeline_read_d_fu_250_d_6_load_out),
    .d_6_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_6_load_out_ap_vld),
    .d_7_load_out(grp_winograd_Pipeline_read_d_fu_250_d_7_load_out),
    .d_7_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_7_load_out_ap_vld),
    .d_8_load_out(grp_winograd_Pipeline_read_d_fu_250_d_8_load_out),
    .d_8_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_8_load_out_ap_vld),
    .d_9_load_out(grp_winograd_Pipeline_read_d_fu_250_d_9_load_out),
    .d_9_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_9_load_out_ap_vld),
    .d_10_load_out(grp_winograd_Pipeline_read_d_fu_250_d_10_load_out),
    .d_10_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_10_load_out_ap_vld),
    .d_11_load_out(grp_winograd_Pipeline_read_d_fu_250_d_11_load_out),
    .d_11_load_out_ap_vld(grp_winograd_Pipeline_read_d_fu_250_d_11_load_out_ap_vld)
);

winograd_winograd_Pipeline_compute_Y grp_winograd_Pipeline_compute_Y_fu_269(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(grp_winograd_Pipeline_compute_Y_fu_269_ap_start),
    .ap_done(grp_winograd_Pipeline_compute_Y_fu_269_ap_done),
    .ap_idle(grp_winograd_Pipeline_compute_Y_fu_269_ap_idle),
    .ap_ready(grp_winograd_Pipeline_compute_Y_fu_269_ap_ready),
    .sub7(reg_331),
    .add10(reg_342),
    .sub5(reg_370),
    .add8(reg_323),
    .p_out(grp_winograd_Pipeline_compute_Y_fu_269_p_out),
    .p_out_ap_vld(grp_winograd_Pipeline_compute_Y_fu_269_p_out_ap_vld),
    .p_out1(grp_winograd_Pipeline_compute_Y_fu_269_p_out1),
    .p_out1_ap_vld(grp_winograd_Pipeline_compute_Y_fu_269_p_out1_ap_vld),
    .p_out2(grp_winograd_Pipeline_compute_Y_fu_269_p_out2),
    .p_out2_ap_vld(grp_winograd_Pipeline_compute_Y_fu_269_p_out2_ap_vld),
    .p_out3(grp_winograd_Pipeline_compute_Y_fu_269_p_out3),
    .p_out3_ap_vld(grp_winograd_Pipeline_compute_Y_fu_269_p_out3_ap_vld)
);

winograd_CTRL_s_axi #(
    .C_S_AXI_ADDR_WIDTH( C_S_AXI_CTRL_ADDR_WIDTH ),
    .C_S_AXI_DATA_WIDTH( C_S_AXI_CTRL_DATA_WIDTH ))
CTRL_s_axi_U(
    .AWVALID(s_axi_CTRL_AWVALID),
    .AWREADY(s_axi_CTRL_AWREADY),
    .AWADDR(s_axi_CTRL_AWADDR),
    .WVALID(s_axi_CTRL_WVALID),
    .WREADY(s_axi_CTRL_WREADY),
    .WDATA(s_axi_CTRL_WDATA),
    .WSTRB(s_axi_CTRL_WSTRB),
    .ARVALID(s_axi_CTRL_ARVALID),
    .ARREADY(s_axi_CTRL_ARREADY),
    .ARADDR(s_axi_CTRL_ARADDR),
    .RVALID(s_axi_CTRL_RVALID),
    .RREADY(s_axi_CTRL_RREADY),
    .RDATA(s_axi_CTRL_RDATA),
    .RRESP(s_axi_CTRL_RRESP),
    .BVALID(s_axi_CTRL_BVALID),
    .BREADY(s_axi_CTRL_BREADY),
    .BRESP(s_axi_CTRL_BRESP),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .in_g(in_g),
    .in_d(in_d),
    .out_y(out_y),
    .ap_start(ap_start),
    .interrupt(interrupt),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_idle(ap_idle)
);

winograd_gmem_m_axi #(
    .CONSERVATIVE( 1 ),
    .USER_MAXREQS( 7 ),
    .MAX_READ_BURST_LENGTH( 16 ),
    .MAX_WRITE_BURST_LENGTH( 16 ),
    .C_M_AXI_ID_WIDTH( C_M_AXI_GMEM_ID_WIDTH ),
    .C_M_AXI_ADDR_WIDTH( C_M_AXI_GMEM_ADDR_WIDTH ),
    .C_M_AXI_DATA_WIDTH( C_M_AXI_GMEM_DATA_WIDTH ),
    .C_M_AXI_AWUSER_WIDTH( C_M_AXI_GMEM_AWUSER_WIDTH ),
    .C_M_AXI_ARUSER_WIDTH( C_M_AXI_GMEM_ARUSER_WIDTH ),
    .C_M_AXI_WUSER_WIDTH( C_M_AXI_GMEM_WUSER_WIDTH ),
    .C_M_AXI_RUSER_WIDTH( C_M_AXI_GMEM_RUSER_WIDTH ),
    .C_M_AXI_BUSER_WIDTH( C_M_AXI_GMEM_BUSER_WIDTH ),
    .C_USER_VALUE( C_M_AXI_GMEM_USER_VALUE ),
    .C_PROT_VALUE( C_M_AXI_GMEM_PROT_VALUE ),
    .C_CACHE_VALUE( C_M_AXI_GMEM_CACHE_VALUE ),
    .CH0_NUM_READ_OUTSTANDING( 16 ),
    .CH0_NUM_WRITE_OUTSTANDING( 16 ),
    .CH0_USER_RFIFONUM_WIDTH( 9 ),
    .CH0_USER_DW( 32 ),
    .CH0_USER_AW( 64 ),
    .NUM_READ_OUTSTANDING( 16 ),
    .NUM_WRITE_OUTSTANDING( 16 ))
gmem_m_axi_U(
    .AWVALID(m_axi_gmem_AWVALID),
    .AWREADY(m_axi_gmem_AWREADY),
    .AWADDR(m_axi_gmem_AWADDR),
    .AWID(m_axi_gmem_AWID),
    .AWLEN(m_axi_gmem_AWLEN),
    .AWSIZE(m_axi_gmem_AWSIZE),
    .AWBURST(m_axi_gmem_AWBURST),
    .AWLOCK(m_axi_gmem_AWLOCK),
    .AWCACHE(m_axi_gmem_AWCACHE),
    .AWPROT(m_axi_gmem_AWPROT),
    .AWQOS(m_axi_gmem_AWQOS),
    .AWREGION(m_axi_gmem_AWREGION),
    .AWUSER(m_axi_gmem_AWUSER),
    .WVALID(m_axi_gmem_WVALID),
    .WREADY(m_axi_gmem_WREADY),
    .WDATA(m_axi_gmem_WDATA),
    .WSTRB(m_axi_gmem_WSTRB),
    .WLAST(m_axi_gmem_WLAST),
    .WID(m_axi_gmem_WID),
    .WUSER(m_axi_gmem_WUSER),
    .ARVALID(m_axi_gmem_ARVALID),
    .ARREADY(m_axi_gmem_ARREADY),
    .ARADDR(m_axi_gmem_ARADDR),
    .ARID(m_axi_gmem_ARID),
    .ARLEN(m_axi_gmem_ARLEN),
    .ARSIZE(m_axi_gmem_ARSIZE),
    .ARBURST(m_axi_gmem_ARBURST),
    .ARLOCK(m_axi_gmem_ARLOCK),
    .ARCACHE(m_axi_gmem_ARCACHE),
    .ARPROT(m_axi_gmem_ARPROT),
    .ARQOS(m_axi_gmem_ARQOS),
    .ARREGION(m_axi_gmem_ARREGION),
    .ARUSER(m_axi_gmem_ARUSER),
    .RVALID(m_axi_gmem_RVALID),
    .RREADY(m_axi_gmem_RREADY),
    .RDATA(m_axi_gmem_RDATA),
    .RLAST(m_axi_gmem_RLAST),
    .RID(m_axi_gmem_RID),
    .RUSER(m_axi_gmem_RUSER),
    .RRESP(m_axi_gmem_RRESP),
    .BVALID(m_axi_gmem_BVALID),
    .BREADY(m_axi_gmem_BREADY),
    .BRESP(m_axi_gmem_BRESP),
    .BID(m_axi_gmem_BID),
    .BUSER(m_axi_gmem_BUSER),
    .ACLK(ap_clk),
    .ARESET(ap_rst_n_inv),
    .ACLK_EN(1'b1),
    .I_CH0_ARVALID(gmem_0_ARVALID),
    .I_CH0_ARREADY(gmem_0_ARREADY),
    .I_CH0_ARADDR(gmem_0_ARADDR),
    .I_CH0_ARLEN(gmem_0_ARLEN),
    .I_CH0_RVALID(gmem_0_RVALID),
    .I_CH0_RREADY(gmem_0_RREADY),
    .I_CH0_RDATA(gmem_0_RDATA),
    .I_CH0_RFIFONUM(gmem_0_RFIFONUM),
    .I_CH0_AWVALID(gmem_0_AWVALID),
    .I_CH0_AWREADY(gmem_0_AWREADY),
    .I_CH0_AWADDR(gmem_addr_2_reg_826),
    .I_CH0_AWLEN(gmem_0_AWLEN),
    .I_CH0_WVALID(gmem_0_WVALID),
    .I_CH0_WREADY(gmem_0_WREADY),
    .I_CH0_WDATA(gmem_0_WDATA),
    .I_CH0_WSTRB(4'd15),
    .I_CH0_BVALID(gmem_0_BVALID),
    .I_CH0_BREADY(gmem_0_BREADY)
);

winograd_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U34(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_281_p0),
    .din1(grp_fu_281_p1),
    .opcode(grp_fu_281_opcode),
    .ce(grp_fu_281_ce),
    .dout(grp_fu_281_p2)
);

winograd_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U35(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_285_p0),
    .din1(grp_fu_285_p1),
    .opcode(grp_fu_285_opcode),
    .ce(grp_fu_285_ce),
    .dout(grp_fu_285_p2)
);

winograd_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U36(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_289_p0),
    .din1(grp_fu_289_p1),
    .opcode(grp_fu_289_opcode),
    .ce(grp_fu_289_ce),
    .dout(grp_fu_289_p2)
);

winograd_faddfsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
faddfsub_32ns_32ns_32_5_full_dsp_1_U37(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_293_p0),
    .din1(grp_fu_293_p1),
    .opcode(grp_fu_293_opcode),
    .ce(1'b1),
    .dout(grp_fu_293_p2)
);

winograd_fsub_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_5_full_dsp_1_U38(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_297_p0),
    .din1(grp_fu_297_p1),
    .ce(1'b1),
    .dout(grp_fu_297_p2)
);

winograd_fadd_32ns_32ns_32_5_full_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 5 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fadd_32ns_32ns_32_5_full_dsp_1_U39(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_winograd_Pipeline_read_d_fu_250_d_6_load_out),
    .din1(grp_winograd_Pipeline_read_d_fu_250_d_10_load_out),
    .ce(1'b1),
    .dout(grp_fu_301_p2)
);

winograd_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U40(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_308_p0),
    .din1(grp_fu_308_p1),
    .ce(1'b1),
    .dout(grp_fu_308_p2)
);

winograd_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U41(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_313_p0),
    .din1(grp_fu_313_p1),
    .ce(1'b1),
    .dout(grp_fu_313_p2)
);

winograd_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U42(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_318_p0),
    .din1(grp_fu_318_p1),
    .ce(1'b1),
    .dout(grp_fu_318_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_winograd_Pipeline_compute_Y_fu_269_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state53)) begin
            grp_winograd_Pipeline_compute_Y_fu_269_ap_start_reg <= 1'b1;
        end else if ((grp_winograd_Pipeline_compute_Y_fu_269_ap_ready == 1'b1)) begin
            grp_winograd_Pipeline_compute_Y_fu_269_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_winograd_Pipeline_read_d_fu_250_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state20) & (1'b1 == ap_CS_fsm_state19))) begin
            grp_winograd_Pipeline_read_d_fu_250_ap_start_reg <= 1'b1;
        end else if ((grp_winograd_Pipeline_read_d_fu_250_ap_ready == 1'b1)) begin
            grp_winograd_Pipeline_read_d_fu_250_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        grp_winograd_Pipeline_read_g_fu_234_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_NS_fsm_state10) & (1'b1 == ap_CS_fsm_state9))) begin
            grp_winograd_Pipeline_read_g_fu_234_ap_start_reg <= 1'b1;
        end else if ((grp_winograd_Pipeline_read_g_fu_234_ap_ready == 1'b1)) begin
            grp_winograd_Pipeline_read_g_fu_234_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state29)) begin
        add170_2_reg_909 <= grp_fu_301_p2;
        sub160_2_reg_903 <= grp_fu_297_p2;
        sub1_reg_897 <= grp_fu_281_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state34)) begin
        add230_1_reg_933 <= grp_fu_297_p2;
        sub209_1_reg_928 <= grp_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        gmem_addr_2_reg_826 <= sext_ln127_fu_444_p1;
        trunc_ln1_reg_820 <= {{in_d[63:2]}};
        trunc_ln_reg_814 <= {{in_g[63:2]}};
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state38)) begin
        mul266_1_reg_938 <= grp_fu_318_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        mul_1_2_reg_916 <= grp_fu_308_p2;
        sub131_1_reg_923 <= grp_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state16) | ((grp_winograd_Pipeline_read_d_fu_250_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21)))) begin
        reg_323 <= grp_fu_281_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state16) | ((grp_winograd_Pipeline_read_d_fu_250_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21)))) begin
        reg_331 <= grp_fu_285_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state34) | ((grp_winograd_Pipeline_read_d_fu_250_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21)))) begin
        reg_342 <= grp_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state25))) begin
        reg_351 <= grp_fu_308_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state25))) begin
        reg_361 <= grp_fu_313_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state44))) begin
        reg_370 <= grp_fu_281_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state48))) begin
        reg_376 <= grp_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state30))) begin
        reg_383 <= grp_fu_285_p2;
        reg_389 <= grp_fu_289_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state34))) begin
        reg_395 <= grp_fu_308_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state43) | (1'b1 == ap_CS_fsm_state39))) begin
        reg_401 <= grp_fu_313_p2;
        reg_408 <= grp_fu_318_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((grp_winograd_Pipeline_read_g_fu_234_ap_done == 1'b0)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

assign ap_ST_fsm_state14_blk = 1'b0;

assign ap_ST_fsm_state15_blk = 1'b0;

assign ap_ST_fsm_state16_blk = 1'b0;

assign ap_ST_fsm_state17_blk = 1'b0;

assign ap_ST_fsm_state18_blk = 1'b0;

assign ap_ST_fsm_state19_blk = 1'b0;

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state20_blk = 1'b0;

always @ (*) begin
    if ((grp_winograd_Pipeline_read_d_fu_250_ap_done == 1'b0)) begin
        ap_ST_fsm_state21_blk = 1'b1;
    end else begin
        ap_ST_fsm_state21_blk = 1'b0;
    end
end

assign ap_ST_fsm_state22_blk = 1'b0;

assign ap_ST_fsm_state23_blk = 1'b0;

assign ap_ST_fsm_state24_blk = 1'b0;

assign ap_ST_fsm_state25_blk = 1'b0;

assign ap_ST_fsm_state26_blk = 1'b0;

assign ap_ST_fsm_state27_blk = 1'b0;

assign ap_ST_fsm_state28_blk = 1'b0;

assign ap_ST_fsm_state29_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_ARREADY == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state30_blk = 1'b0;

assign ap_ST_fsm_state31_blk = 1'b0;

assign ap_ST_fsm_state32_blk = 1'b0;

assign ap_ST_fsm_state33_blk = 1'b0;

assign ap_ST_fsm_state34_blk = 1'b0;

assign ap_ST_fsm_state35_blk = 1'b0;

assign ap_ST_fsm_state36_blk = 1'b0;

assign ap_ST_fsm_state37_blk = 1'b0;

assign ap_ST_fsm_state38_blk = 1'b0;

assign ap_ST_fsm_state39_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state40_blk = 1'b0;

assign ap_ST_fsm_state41_blk = 1'b0;

assign ap_ST_fsm_state42_blk = 1'b0;

assign ap_ST_fsm_state43_blk = 1'b0;

assign ap_ST_fsm_state44_blk = 1'b0;

assign ap_ST_fsm_state45_blk = 1'b0;

assign ap_ST_fsm_state46_blk = 1'b0;

assign ap_ST_fsm_state47_blk = 1'b0;

assign ap_ST_fsm_state48_blk = 1'b0;

assign ap_ST_fsm_state49_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state50_blk = 1'b0;

assign ap_ST_fsm_state51_blk = 1'b0;

assign ap_ST_fsm_state52_blk = 1'b0;

assign ap_ST_fsm_state53_blk = 1'b0;

always @ (*) begin
    if ((grp_winograd_Pipeline_compute_Y_fu_269_ap_done == 1'b0)) begin
        ap_ST_fsm_state54_blk = 1'b1;
    end else begin
        ap_ST_fsm_state54_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_AWREADY == 1'b0)) begin
        ap_ST_fsm_state55_blk = 1'b1;
    end else begin
        ap_ST_fsm_state55_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state56_blk = 1'b1;
    end else begin
        ap_ST_fsm_state56_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state57_blk = 1'b1;
    end else begin
        ap_ST_fsm_state57_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state58_blk = 1'b1;
    end else begin
        ap_ST_fsm_state58_blk = 1'b0;
    end
end

always @ (*) begin
    if ((gmem_0_WREADY == 1'b0)) begin
        ap_ST_fsm_state59_blk = 1'b1;
    end else begin
        ap_ST_fsm_state59_blk = 1'b0;
    end
end

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state60_blk = 1'b0;

assign ap_ST_fsm_state61_blk = 1'b0;

assign ap_ST_fsm_state62_blk = 1'b0;

assign ap_ST_fsm_state63_blk = 1'b0;

always @ (*) begin
    if ((gmem_0_BVALID == 1'b0)) begin
        ap_ST_fsm_state64_blk = 1'b1;
    end else begin
        ap_ST_fsm_state64_blk = 1'b0;
    end
end

assign ap_ST_fsm_state6_blk = 1'b0;

assign ap_ST_fsm_state7_blk = 1'b0;

assign ap_ST_fsm_state8_blk = 1'b0;

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state64))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state64))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        gmem_0_ARADDR = sext_ln45_fu_480_p1;
    end else if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_0_ARADDR = sext_ln34_fu_454_p1;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_0_ARADDR = grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARADDR;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_0_ARADDR = grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARADDR;
    end else begin
        gmem_0_ARADDR = 'bx;
    end
end

always @ (*) begin
    if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
        gmem_0_ARLEN = 64'd16;
    end else if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        gmem_0_ARLEN = 64'd9;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_0_ARLEN = grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARLEN;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_0_ARLEN = grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARLEN;
    end else begin
        gmem_0_ARLEN = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12)) | ((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2)))) begin
        gmem_0_ARVALID = 1'b1;
    end else if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_0_ARVALID = grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_ARVALID;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_0_ARVALID = grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_ARVALID;
    end else begin
        gmem_0_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
        gmem_0_AWVALID = 1'b1;
    end else begin
        gmem_0_AWVALID = 1'b0;
    end
end

always @ (*) begin
    if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state64))) begin
        gmem_0_BREADY = 1'b1;
    end else begin
        gmem_0_BREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state21))) begin
        gmem_0_RREADY = grp_winograd_Pipeline_read_d_fu_250_m_axi_gmem_0_RREADY;
    end else if (((1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10))) begin
        gmem_0_RREADY = grp_winograd_Pipeline_read_g_fu_234_m_axi_gmem_0_RREADY;
    end else begin
        gmem_0_RREADY = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        gmem_0_WDATA = bitcast_ln127_3_fu_659_p1;
    end else if ((1'b1 == ap_CS_fsm_state58)) begin
        gmem_0_WDATA = bitcast_ln127_2_fu_651_p1;
    end else if ((1'b1 == ap_CS_fsm_state57)) begin
        gmem_0_WDATA = bitcast_ln127_1_fu_643_p1;
    end else if ((1'b1 == ap_CS_fsm_state56)) begin
        gmem_0_WDATA = bitcast_ln127_fu_635_p1;
    end else begin
        gmem_0_WDATA = 'bx;
    end
end

always @ (*) begin
    if ((((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state59)) | ((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state58)) | ((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state57)) | ((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state56)))) begin
        gmem_0_WVALID = 1'b1;
    end else begin
        gmem_0_WVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state12) | (1'b1 == ap_CS_fsm_state2))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state55)) begin
        gmem_blk_n_AW = m_axi_gmem_AWREADY;
    end else begin
        gmem_blk_n_AW = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state64)) begin
        gmem_blk_n_B = m_axi_gmem_BVALID;
    end else begin
        gmem_blk_n_B = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56))) begin
        gmem_blk_n_W = m_axi_gmem_WREADY;
    end else begin
        gmem_blk_n_W = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((gmem_0_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state12)) | ((grp_winograd_Pipeline_read_d_fu_250_ap_done == 1'b0) & (1'b1 == ap_CS_fsm_state21)))) begin
        grp_fu_281_ce = 1'b0;
    end else begin
        grp_fu_281_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state25))) begin
        grp_fu_281_opcode = 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_281_opcode = 2'd0;
    end else begin
        grp_fu_281_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_281_p0 = reg_331;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        grp_fu_281_p0 = grp_winograd_Pipeline_read_d_fu_250_d_3_load_out;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        grp_fu_281_p0 = reg_351;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_fu_281_p0 = reg_383;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_281_p0 = sub1_reg_897;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_281_p0 = grp_winograd_Pipeline_read_d_fu_250_d_load_out;
    end else if (((1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state35))) begin
        grp_fu_281_p0 = reg_342;
    end else if (((1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state44))) begin
        grp_fu_281_p0 = reg_323;
    end else if (((1'b1 == ap_CS_fsm_state21) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_281_p0 = grp_winograd_Pipeline_read_g_fu_234_g_load_out;
    end else begin
        grp_fu_281_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state44))) begin
        grp_fu_281_p1 = reg_351;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        grp_fu_281_p1 = grp_winograd_Pipeline_read_d_fu_250_d_11_load_out;
    end else if ((1'b1 == ap_CS_fsm_state39)) begin
        grp_fu_281_p1 = reg_361;
    end else if (((1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state30))) begin
        grp_fu_281_p1 = sub160_2_reg_903;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state26))) begin
        grp_fu_281_p1 = grp_winograd_Pipeline_read_g_fu_234_g_6_load_out;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_281_p1 = grp_winograd_Pipeline_read_d_fu_250_d_8_load_out;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_281_p1 = grp_winograd_Pipeline_read_g_fu_234_g_8_load_out;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_fu_281_p1 = grp_winograd_Pipeline_read_g_fu_234_g_3_load_out;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_281_p1 = grp_winograd_Pipeline_read_g_fu_234_g_2_load_out;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_281_p1 = grp_winograd_Pipeline_read_g_fu_234_g_1_load_out;
    end else begin
        grp_fu_281_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state24) | (1'b1 == ap_CS_fsm_state23) | (1'b1 == ap_CS_fsm_state22) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state54) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | (1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state64) | (1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state58) | (1'b1 == ap_CS_fsm_state57) | (1'b1 == ap_CS_fsm_state56) | (1'b1 == ap_CS_fsm_state55) | (1'b1 == ap_CS_fsm_state2) | (1'b1 == ap_CS_fsm_state63) | (1'b1 == ap_CS_fsm_state62) | (1'b1 == ap_CS_fsm_state61) | (1'b1 == ap_CS_fsm_state60) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | ((gmem_0_ARREADY == 1'b0) & (1'b1 == ap_CS_fsm_state12)) | ((grp_winograd_Pipeline_read_d_fu_250_ap_done == 1'b0) & (1'b1 == ap_CS_fsm_state21)))) begin
        grp_fu_285_ce = 1'b0;
    end else begin
        grp_fu_285_ce = 1'b1;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state44))) begin
        grp_fu_285_opcode = 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state12))) begin
        grp_fu_285_opcode = 2'd0;
    end else begin
        grp_fu_285_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_285_p0 = reg_361;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        grp_fu_285_p0 = grp_winograd_Pipeline_read_d_fu_250_d_7_load_out;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_285_p0 = reg_376;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_fu_285_p0 = reg_389;
    end else if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state30))) begin
        grp_fu_285_p0 = reg_342;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_285_p0 = grp_winograd_Pipeline_read_g_fu_234_g_load_out;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_285_p0 = grp_winograd_Pipeline_read_d_fu_250_d_4_load_out;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_285_p0 = reg_331;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_285_p0 = grp_winograd_Pipeline_read_g_fu_234_g_3_load_out;
    end else begin
        grp_fu_285_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_285_p1 = reg_361;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_285_p1 = reg_351;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        grp_fu_285_p1 = grp_winograd_Pipeline_read_d_fu_250_d_11_load_out;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_285_p1 = add170_2_reg_909;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_fu_285_p1 = mul_1_2_reg_916;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_285_p1 = sub160_2_reg_903;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_285_p1 = grp_winograd_Pipeline_read_g_fu_234_g_3_load_out;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_285_p1 = grp_winograd_Pipeline_read_d_fu_250_d_8_load_out;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_285_p1 = grp_winograd_Pipeline_read_g_fu_234_g_5_load_out;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_fu_285_p1 = grp_winograd_Pipeline_read_g_fu_234_g_4_load_out;
    end else begin
        grp_fu_285_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state45) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state38) | (1'b1 == ap_CS_fsm_state53) | (1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state29) | (1'b1 == ap_CS_fsm_state48) | (1'b1 == ap_CS_fsm_state39) | (1'b1 == ap_CS_fsm_state34) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state25) | (1'b1 == ap_CS_fsm_state52) | (1'b1 == ap_CS_fsm_state51) | (1'b1 == ap_CS_fsm_state50) | (1'b1 == ap_CS_fsm_state47) | (1'b1 == ap_CS_fsm_state46) | (1'b1 == ap_CS_fsm_state37) | (1'b1 == ap_CS_fsm_state33) | (1'b1 == ap_CS_fsm_state32) | (1'b1 == ap_CS_fsm_state28) | ((grp_winograd_Pipeline_read_d_fu_250_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21)))) begin
        grp_fu_289_ce = 1'b1;
    end else begin
        grp_fu_289_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state30) | (1'b1 == ap_CS_fsm_state25))) begin
        grp_fu_289_opcode = 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state35) | (1'b1 == ap_CS_fsm_state26))) begin
        grp_fu_289_opcode = 2'd0;
    end else begin
        grp_fu_289_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state49)) begin
        grp_fu_289_p0 = reg_376;
    end else if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_289_p0 = reg_401;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_289_p0 = add230_1_reg_933;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_fu_289_p0 = sub131_1_reg_923;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_289_p0 = reg_342;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_289_p0 = reg_351;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_289_p0 = grp_winograd_Pipeline_read_d_fu_250_d_1_load_out;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_289_p0 = grp_winograd_Pipeline_read_g_fu_234_g_6_load_out;
    end else begin
        grp_fu_289_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state49) | (1'b1 == ap_CS_fsm_state44))) begin
        grp_fu_289_p1 = reg_408;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_289_p1 = add170_2_reg_909;
    end else if ((1'b1 == ap_CS_fsm_state31)) begin
        grp_fu_289_p1 = mul_1_2_reg_916;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_289_p1 = sub1_reg_897;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_289_p1 = reg_361;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_289_p1 = grp_winograd_Pipeline_read_d_fu_250_d_9_load_out;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        grp_fu_289_p1 = grp_winograd_Pipeline_read_g_fu_234_g_7_load_out;
    end else begin
        grp_fu_289_p1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state26) | (1'b1 == ap_CS_fsm_state30))) begin
        grp_fu_293_opcode = 2'd1;
    end else if (((1'b1 == ap_CS_fsm_state44) | (1'b1 == ap_CS_fsm_state25))) begin
        grp_fu_293_opcode = 2'd0;
    end else begin
        grp_fu_293_opcode = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_293_p0 = mul266_1_reg_938;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_293_p0 = reg_331;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_293_p0 = reg_351;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_293_p0 = grp_winograd_Pipeline_read_d_fu_250_d_5_load_out;
    end else begin
        grp_fu_293_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state44)) begin
        grp_fu_293_p1 = reg_401;
    end else if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_293_p1 = add170_2_reg_909;
    end else if ((1'b1 == ap_CS_fsm_state26)) begin
        grp_fu_293_p1 = reg_361;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_293_p1 = grp_winograd_Pipeline_read_d_fu_250_d_9_load_out;
    end else begin
        grp_fu_293_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_297_p0 = reg_376;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_297_p0 = grp_winograd_Pipeline_read_d_fu_250_d_2_load_out;
    end else begin
        grp_fu_297_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state30)) begin
        grp_fu_297_p1 = reg_331;
    end else if ((1'b1 == ap_CS_fsm_state25)) begin
        grp_fu_297_p1 = grp_winograd_Pipeline_read_d_fu_250_d_10_load_out;
    end else begin
        grp_fu_297_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_308_p0 = grp_winograd_Pipeline_read_g_fu_234_g_6_load_out;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        grp_fu_308_p0 = reg_395;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_308_p0 = grp_winograd_Pipeline_read_g_fu_234_g_load_out;
    end else if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state27))) begin
        grp_fu_308_p0 = reg_370;
    end else if (((1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state22))) begin
        grp_fu_308_p0 = reg_323;
    end else begin
        grp_fu_308_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_308_p1 = bitcast_ln93_1_fu_592_p1;
    end else if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state35))) begin
        grp_fu_308_p1 = reg_323;
    end else if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state27) | (1'b1 == ap_CS_fsm_state31) | (1'b1 == ap_CS_fsm_state22))) begin
        grp_fu_308_p1 = 32'd1056964608;
    end else begin
        grp_fu_308_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_313_p0 = mul_1_2_reg_916;
    end else if ((1'b1 == ap_CS_fsm_state40)) begin
        grp_fu_313_p0 = reg_401;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_fu_313_p0 = reg_383;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_313_p0 = reg_395;
    end else if ((1'b1 == ap_CS_fsm_state22)) begin
        grp_fu_313_p0 = reg_331;
    end else begin
        grp_fu_313_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state45)) begin
        grp_fu_313_p1 = bitcast_ln93_3_fu_627_p1;
    end else if (((1'b1 == ap_CS_fsm_state40) | (1'b1 == ap_CS_fsm_state35))) begin
        grp_fu_313_p1 = reg_331;
    end else if (((1'b1 == ap_CS_fsm_state36) | (1'b1 == ap_CS_fsm_state22))) begin
        grp_fu_313_p1 = 32'd1056964608;
    end else begin
        grp_fu_313_p1 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        grp_fu_318_p0 = reg_408;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_fu_318_p0 = reg_389;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_318_p0 = reg_351;
    end else begin
        grp_fu_318_p0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state40)) begin
        grp_fu_318_p1 = reg_342;
    end else if ((1'b1 == ap_CS_fsm_state36)) begin
        grp_fu_318_p1 = 32'd1056964608;
    end else if ((1'b1 == ap_CS_fsm_state35)) begin
        grp_fu_318_p1 = sub209_1_reg_928;
    end else begin
        grp_fu_318_p1 = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((grp_winograd_Pipeline_read_g_fu_234_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((gmem_0_ARREADY == 1'b1) & (1'b1 == ap_CS_fsm_state12))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state20;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            if (((grp_winograd_Pipeline_read_d_fu_250_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state21))) begin
                ap_NS_fsm = ap_ST_fsm_state22;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state21;
            end
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state26;
        end
        ap_ST_fsm_state26 : begin
            ap_NS_fsm = ap_ST_fsm_state27;
        end
        ap_ST_fsm_state27 : begin
            ap_NS_fsm = ap_ST_fsm_state28;
        end
        ap_ST_fsm_state28 : begin
            ap_NS_fsm = ap_ST_fsm_state29;
        end
        ap_ST_fsm_state29 : begin
            ap_NS_fsm = ap_ST_fsm_state30;
        end
        ap_ST_fsm_state30 : begin
            ap_NS_fsm = ap_ST_fsm_state31;
        end
        ap_ST_fsm_state31 : begin
            ap_NS_fsm = ap_ST_fsm_state32;
        end
        ap_ST_fsm_state32 : begin
            ap_NS_fsm = ap_ST_fsm_state33;
        end
        ap_ST_fsm_state33 : begin
            ap_NS_fsm = ap_ST_fsm_state34;
        end
        ap_ST_fsm_state34 : begin
            ap_NS_fsm = ap_ST_fsm_state35;
        end
        ap_ST_fsm_state35 : begin
            ap_NS_fsm = ap_ST_fsm_state36;
        end
        ap_ST_fsm_state36 : begin
            ap_NS_fsm = ap_ST_fsm_state37;
        end
        ap_ST_fsm_state37 : begin
            ap_NS_fsm = ap_ST_fsm_state38;
        end
        ap_ST_fsm_state38 : begin
            ap_NS_fsm = ap_ST_fsm_state39;
        end
        ap_ST_fsm_state39 : begin
            ap_NS_fsm = ap_ST_fsm_state40;
        end
        ap_ST_fsm_state40 : begin
            ap_NS_fsm = ap_ST_fsm_state41;
        end
        ap_ST_fsm_state41 : begin
            ap_NS_fsm = ap_ST_fsm_state42;
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_state43;
        end
        ap_ST_fsm_state43 : begin
            ap_NS_fsm = ap_ST_fsm_state44;
        end
        ap_ST_fsm_state44 : begin
            ap_NS_fsm = ap_ST_fsm_state45;
        end
        ap_ST_fsm_state45 : begin
            ap_NS_fsm = ap_ST_fsm_state46;
        end
        ap_ST_fsm_state46 : begin
            ap_NS_fsm = ap_ST_fsm_state47;
        end
        ap_ST_fsm_state47 : begin
            ap_NS_fsm = ap_ST_fsm_state48;
        end
        ap_ST_fsm_state48 : begin
            ap_NS_fsm = ap_ST_fsm_state49;
        end
        ap_ST_fsm_state49 : begin
            ap_NS_fsm = ap_ST_fsm_state50;
        end
        ap_ST_fsm_state50 : begin
            ap_NS_fsm = ap_ST_fsm_state51;
        end
        ap_ST_fsm_state51 : begin
            ap_NS_fsm = ap_ST_fsm_state52;
        end
        ap_ST_fsm_state52 : begin
            ap_NS_fsm = ap_ST_fsm_state53;
        end
        ap_ST_fsm_state53 : begin
            ap_NS_fsm = ap_ST_fsm_state54;
        end
        ap_ST_fsm_state54 : begin
            if (((grp_winograd_Pipeline_compute_Y_fu_269_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state54))) begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state54;
            end
        end
        ap_ST_fsm_state55 : begin
            if (((gmem_0_AWREADY == 1'b1) & (1'b1 == ap_CS_fsm_state55))) begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state55;
            end
        end
        ap_ST_fsm_state56 : begin
            if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state56))) begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state56;
            end
        end
        ap_ST_fsm_state57 : begin
            if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state57))) begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state57;
            end
        end
        ap_ST_fsm_state58 : begin
            if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state58))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state58;
            end
        end
        ap_ST_fsm_state59 : begin
            if (((gmem_0_WREADY == 1'b1) & (1'b1 == ap_CS_fsm_state59))) begin
                ap_NS_fsm = ap_ST_fsm_state60;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end
        end
        ap_ST_fsm_state60 : begin
            ap_NS_fsm = ap_ST_fsm_state61;
        end
        ap_ST_fsm_state61 : begin
            ap_NS_fsm = ap_ST_fsm_state62;
        end
        ap_ST_fsm_state62 : begin
            ap_NS_fsm = ap_ST_fsm_state63;
        end
        ap_ST_fsm_state63 : begin
            ap_NS_fsm = ap_ST_fsm_state64;
        end
        ap_ST_fsm_state64 : begin
            if (((gmem_0_BVALID == 1'b1) & (1'b1 == ap_CS_fsm_state64))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state64;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state22 = ap_CS_fsm[32'd21];

assign ap_CS_fsm_state23 = ap_CS_fsm[32'd22];

assign ap_CS_fsm_state24 = ap_CS_fsm[32'd23];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state26 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_state27 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_state28 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_state29 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state30 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state31 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_state32 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_state33 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_state34 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state35 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state36 = ap_CS_fsm[32'd35];

assign ap_CS_fsm_state37 = ap_CS_fsm[32'd36];

assign ap_CS_fsm_state38 = ap_CS_fsm[32'd37];

assign ap_CS_fsm_state39 = ap_CS_fsm[32'd38];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state40 = ap_CS_fsm[32'd39];

assign ap_CS_fsm_state43 = ap_CS_fsm[32'd42];

assign ap_CS_fsm_state44 = ap_CS_fsm[32'd43];

assign ap_CS_fsm_state45 = ap_CS_fsm[32'd44];

assign ap_CS_fsm_state46 = ap_CS_fsm[32'd45];

assign ap_CS_fsm_state47 = ap_CS_fsm[32'd46];

assign ap_CS_fsm_state48 = ap_CS_fsm[32'd47];

assign ap_CS_fsm_state49 = ap_CS_fsm[32'd48];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state50 = ap_CS_fsm[32'd49];

assign ap_CS_fsm_state51 = ap_CS_fsm[32'd50];

assign ap_CS_fsm_state52 = ap_CS_fsm[32'd51];

assign ap_CS_fsm_state53 = ap_CS_fsm[32'd52];

assign ap_CS_fsm_state54 = ap_CS_fsm[32'd53];

assign ap_CS_fsm_state55 = ap_CS_fsm[32'd54];

assign ap_CS_fsm_state56 = ap_CS_fsm[32'd55];

assign ap_CS_fsm_state57 = ap_CS_fsm[32'd56];

assign ap_CS_fsm_state58 = ap_CS_fsm[32'd57];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd58];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state60 = ap_CS_fsm[32'd59];

assign ap_CS_fsm_state61 = ap_CS_fsm[32'd60];

assign ap_CS_fsm_state62 = ap_CS_fsm[32'd61];

assign ap_CS_fsm_state63 = ap_CS_fsm[32'd62];

assign ap_CS_fsm_state64 = ap_CS_fsm[32'd63];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign ap_NS_fsm_state10 = ap_NS_fsm[32'd9];

assign ap_NS_fsm_state20 = ap_NS_fsm[32'd19];

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign bit_sel1_fu_566_p3 = bitcast_ln93_fu_562_p1[32'd31];

assign bit_sel_fu_601_p3 = bitcast_ln93_2_fu_597_p1[32'd31];

assign bitcast_ln127_1_fu_643_p1 = grp_winograd_Pipeline_compute_Y_fu_269_p_out2;

assign bitcast_ln127_2_fu_651_p1 = grp_winograd_Pipeline_compute_Y_fu_269_p_out1;

assign bitcast_ln127_3_fu_659_p1 = grp_winograd_Pipeline_compute_Y_fu_269_p_out;

assign bitcast_ln127_fu_635_p1 = grp_winograd_Pipeline_compute_Y_fu_269_p_out3;

assign bitcast_ln93_1_fu_592_p1 = xor_ln_fu_584_p3;

assign bitcast_ln93_2_fu_597_p1 = reg_331;

assign bitcast_ln93_3_fu_627_p1 = xor_ln93_1_fu_619_p3;

assign bitcast_ln93_fu_562_p1 = reg_370;

assign gmem_0_AWLEN = 64'd4;

assign grp_winograd_Pipeline_compute_Y_fu_269_ap_start = grp_winograd_Pipeline_compute_Y_fu_269_ap_start_reg;

assign grp_winograd_Pipeline_read_d_fu_250_ap_start = grp_winograd_Pipeline_read_d_fu_250_ap_start_reg;

assign grp_winograd_Pipeline_read_g_fu_234_ap_start = grp_winograd_Pipeline_read_g_fu_234_ap_start_reg;

assign sext_ln127_fu_444_p1 = $signed(trunc_ln2_fu_434_p4);

assign sext_ln34_fu_454_p1 = $signed(trunc_ln_reg_814);

assign sext_ln45_fu_480_p1 = $signed(trunc_ln1_reg_820);

assign trunc_ln2_fu_434_p4 = {{out_y[63:2]}};

assign trunc_ln93_1_fu_615_p1 = bitcast_ln93_2_fu_597_p1[30:0];

assign trunc_ln93_fu_580_p1 = bitcast_ln93_fu_562_p1[30:0];

assign xor_ln93_1_fu_619_p3 = {{xor_ln93_fu_609_p2}, {trunc_ln93_1_fu_615_p1}};

assign xor_ln93_2_fu_574_p2 = (bit_sel1_fu_566_p3 ^ 1'd1);

assign xor_ln93_fu_609_p2 = (bit_sel_fu_601_p3 ^ 1'd1);

assign xor_ln_fu_584_p3 = {{xor_ln93_2_fu_574_p2}, {trunc_ln93_fu_580_p1}};

endmodule //winograd
