# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/winograd_fadd_32ns_32ns_32_5_full_dsp_1_ip/winograd_fadd_32ns_32ns_32_5_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==winograd_fadd_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==winograd_fadd_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# IP: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/winograd_faddfsub_32ns_32ns_32_5_full_dsp_1_ip/winograd_faddfsub_32ns_32ns_32_5_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==winograd_faddfsub_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==winograd_faddfsub_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# IP: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/winograd_fmul_32ns_32ns_32_4_max_dsp_1_ip/winograd_fmul_32ns_32ns_32_4_max_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==winograd_fmul_32ns_32ns_32_4_max_dsp_1_ip || ORIG_REF_NAME==winograd_fmul_32ns_32ns_32_4_max_dsp_1_ip} -quiet] -quiet

# IP: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/winograd_fsub_32ns_32ns_32_5_full_dsp_1_ip/winograd_fsub_32ns_32ns_32_5_full_dsp_1_ip.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==winograd_fsub_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==winograd_fsub_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# XDC: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/winograd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.srcs/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/bd_0_hls_inst_0.xci
# IP: The module: 'bd_0_hls_inst_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/winograd_fadd_32ns_32ns_32_5_full_dsp_1_ip/winograd_fadd_32ns_32ns_32_5_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==winograd_fadd_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==winograd_fadd_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# IP: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/winograd_faddfsub_32ns_32ns_32_5_full_dsp_1_ip/winograd_faddfsub_32ns_32ns_32_5_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==winograd_faddfsub_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==winograd_faddfsub_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# IP: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/winograd_fmul_32ns_32ns_32_4_max_dsp_1_ip/winograd_fmul_32ns_32ns_32_4_max_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==winograd_fmul_32ns_32ns_32_4_max_dsp_1_ip || ORIG_REF_NAME==winograd_fmul_32ns_32ns_32_4_max_dsp_1_ip} -quiet] -quiet

# IP: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/hdl/ip/winograd_fsub_32ns_32ns_32_5_full_dsp_1_ip/winograd_fsub_32ns_32ns_32_5_full_dsp_1_ip.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==winograd_fsub_32ns_32ns_32_5_full_dsp_1_ip || ORIG_REF_NAME==winograd_fsub_32ns_32ns_32_5_full_dsp_1_ip} -quiet] -quiet

# XDC: /home/nirmal-thomas/Documents/dev/hls_dev/hardware_acc/convolution_accelerator/convolution_accelerator/hls/impl/verilog/project.gen/sources_1/bd/bd_0/ip/bd_0_hls_inst_0/constraints/winograd_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bd_0_hls_inst_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
